# 导入包

In [1]:
import numpy as np
from scipy import linalg

# 改进平方根算法

In [56]:
def adjust_cholesky(A):
    n = len(A)
    L = np.tril(np.ones([n,n]))
    d = []
    [d.append(i) for i in range(n)]
    c = np.zeros([n,n])
    for i in range(n):
        for j in range(i):
            s = 0
            for m in range(j):
                s += c[i][m]*L[j][m]
            c[i][j] = A[i][j] - s
            L[i][j] = c[i][j] / d[j]
        s = 0
        for m in range(i):
            s += c[i][m]*L[i][m]
        d[i] = A[i][i] - s
    return L,d

In [57]:
init = np.array([2,4,2,4,9,6,2,6,8]).reshape(3,3)
L,d = adjust_cholesky(init)

In [58]:
L

array([[1., 0., 0.],
       [2., 1., 0.],
       [1., 2., 1.]])

In [59]:
d

[2, 1.0, 2.0]

In [60]:
np.dot(np.dot(L,np.diag(d)),L.T)

array([[2., 4., 2.],
       [4., 9., 6.],
       [2., 6., 8.]])

# 计算解

In [68]:
b = np.array([0,-1,-4]).reshape(3,1)
Y = linalg.solve(L,b)
Z = linalg.solve(np.diag(d),Y)
X = linalg.solve(L.T,Z)

In [69]:
print(Y)
print(Z)
print(X)

[[ 0.]
 [-1.]
 [-2.]]
[[ 0.]
 [-1.]
 [-1.]]
[[-1.]
 [ 1.]
 [-1.]]
