# 导入包

In [1]:
import numpy as np
from scipy import linalg

# Doolittle分解

In [3]:
def doolittle(a):
    n = len(a)
    L = np.tril(np.ones([n,n]))
    U = np.triu(np.ones([n,n]))
    for j in range(n):
        U[0][j] = a[0][j]
    for i in range(n):
        L[i][0] = a[i][0]/U[0][0]
    for k in range(1,n):
        for j in range(k,n):
            s = 0
            for m in range(k):
                s += L[k][m]*U[m][j]
            U[k][j] = a[k][j]-s
        for i in range(k+1,n):
            s = 0
            for m in range(k):
                s += L[i][m]*U[m][k]
            L[i][k] = (a[i][k]-s)/U[k][k]
    return U,L

# Crout 分解法

In [4]:
def crout(a):
    n = len(a)
    L = np.tril(np.ones([n,n]))
    U = np.triu(np.ones([n,n]))
    for i in range(n):
        L[i][0] = a[i][0]
    for j in range(n):
        U[0][j] = a[0][j]/L[0][0]
    for k in range(1,n):
        for i in range(k,n):
            s = 0
            for m in range(k):
                s += L[i][m]*U[m][k]
            L[i][k] = a[i][k]-s
        for j in range(k+1,n):
            s = 0
            for m in range(k):
                s += L[k][m]*U[m][j]
            U[k][j] = (a[k][j]-s)/L[k][k]
    return U,L

# 计算

In [5]:
init = np.array([3,1,1,6,5,3,6,8,7]).reshape(3,3)
U1,L1 = doolittle(init)
U2,L2 = crout(init)

In [6]:
U1

array([[3., 1., 1.],
       [0., 3., 1.],
       [0., 0., 3.]])

In [7]:
L1

array([[1., 0., 0.],
       [2., 1., 0.],
       [2., 2., 1.]])

In [8]:
np.dot(L1,U1)

array([[3., 1., 1.],
       [6., 5., 3.],
       [6., 8., 7.]])

In [9]:
U2

array([[1.        , 0.33333333, 0.33333333],
       [0.        , 1.        , 0.33333333],
       [0.        , 0.        , 1.        ]])

In [10]:
L2

array([[3., 0., 0.],
       [6., 3., 0.],
       [6., 6., 3.]])

In [11]:
np.dot(L2,U2)

array([[3., 1., 1.],
       [6., 5., 3.],
       [6., 8., 7.]])

# LUX = b 设 UX=y
先求解y<br>
后求解x

In [16]:
b = np.array([[4],[9],[13]])
y = linalg.solve(L2,b)
x = linalg.solve(U2,y)

In [17]:
y

array([[1.33333333],
       [0.33333333],
       [1.        ]])

In [14]:
x

array([1., 0., 1.])

In [18]:
b

array([[ 4],
       [ 9],
       [13]])